export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const YELLOW_COLOR = 'YELLOW_COLOR';
export const GREEN_COLOR = 'GREEN_COLOR';
export const REDIRECT = 'REDIRECT';